export enum SET_SETTINGS_ACTIONS_ENUM {
  SET_LIMIT = "SET_LIMIT",
  SET_TYPES = "SET_TYPES",
  SET_QUANTITY = "SET_QUANTITY",
  SET_CAN_MODIFY_ANSWER = "SET_CAN_MODIFY_ANSWER",
  SET_BASE_VALUE = "SET_BASE_VALUE",
  RESET_BASE_VALUES = "RESET_BASE_VALUES",
  SELECT_ALL_BASE_VALUES = "SELECT_ALL_BASE_VALUES",
  SET_SHOULD_SHUFFLE_EXAMPLES = "SET_SHOULD_SHUFFLE_EXAMPLES",
}
