import { TASK_LEVELS_ENUM } from "../enums/tasks-levels.enum";
import { TASKS_TYPES_ENUM } from "../enums/tasks-types.enum";
import { TTask } from "../types/task.type";

export const TASK_LIST: TTask[] = [
  // ========== SUM ==========
  // SUM EASY (17 задач, ответы разнообразны: 3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,10,10)
  {
    id: 1,
    description: "У Миши 1 конфета, у Кати 2. Сколько всего?",
    answer: 3,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 2,
    description: "На столе 2 книги и 2 тетради. Сколько предметов?",
    answer: 4,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 3,
    description: "В вазе 3 яблока и 1 груша. Сколько фруктов?",
    answer: 4,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 4,
    description: "Маша съела 2 пирожка, Саша 3. Сколько всего?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 5,
    description: "В аквариуме 4 рыбки, в другом 1. Сколько рыбок?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 6,
    description: "У Лены 3 открытки, у Оли 3. Сколько открыток?",
    answer: 6,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 7,
    description: "На полке 2 синие машинки и 4 красные. Сколько машинок?",
    answer: 6,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 8,
    description: "На горке 2 девочки и 5 мальчиков. Сколько детей?",
    answer: 7,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 9,
    description: "В коробке 3 зелёных и 4 синих карандаша. Сколько карандашей?",
    answer: 7,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 10,
    description: "У Пети 5 рублей, у Коли 3. Сколько денег?",
    answer: 8,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 11,
    description: "В пенале 2 ручки и 6 фломастеров. Сколько предметов?",
    answer: 8,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 12,
    description: "На дереве 4 вороны и 5 сорок. Сколько птиц?",
    answer: 9,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 13,
    description: "В букете 3 розы и 6 тюльпанов. Сколько цветов?",
    answer: 9,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 14,
    description: "У бабушки 3 белых и 7 серых кроликов. Сколько кроликов?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 15,
    description: "В гараже 2 грузовика и 8 легковых машин. Сколько машин?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 16,
    description: "На тарелке 4 пирожка и 6 булочек. Сколько выпечки?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 17,
    description: "В шкафу 5 курток и 5 пальто. Сколько верхней одежды?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },

  // SUM MID (17 задач, ответы: 12,13,13,14,15,15,16,17,17,18,19,20,20,21,22,23,24)
  {
    id: 18,
    description: "В одной вазе 5 цветов, в другой – 7. Сколько цветов в двух вазах?",
    answer: 12,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 19,
    description: "У Миши 6 конфет, а у Кати 7. Сколько конфет у детей?",
    answer: 13,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 20,
    description: "На одной полке 8 книг, на другой – 5. Сколько книг на обеих полках?",
    answer: 13,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 21,
    description: "В пруду 7 уток и 7 лебедей. Сколько птиц в пруду?",
    answer: 14,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 22,
    description: "На площадке играли 8 девочек и 7 мальчиков. Сколько детей?",
    answer: 15,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 23,
    description: "В коробке 9 синих пуговиц и 6 белых. Сколько пуговиц?",
    answer: 15,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 24,
    description: "В первый день прочитали 8 страниц, во второй – 8. Сколько страниц за два дня?",
    answer: 16,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 25,
    description: "Купили 6 кг яблок и 11 кг груш. Сколько кг фруктов?",
    answer: 17,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 26,
    description: "У Лены 9 наклеек, у Кати – 8. Сколько наклеек у обеих?",
    answer: 17,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 27,
    description: "В гараже 10 легковых и 8 грузовых машин. Сколько всего?",
    answer: 18,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 28,
    description: "На столе 11 тетрадей и 8 книг. Сколько предметов?",
    answer: 19,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 29,
    description: "В букете 10 ромашек и 10 васильков. Сколько цветов?",
    answer: 20,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 30,
    description: "У Пети 12 рублей, у Саши – 8. Сколько денег у мальчиков?",
    answer: 20,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 31,
    description: "В ящике 9 яблок и 12 груш. Сколько фруктов?",
    answer: 21,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 32,
    description: "На парковке 12 белых и 10 чёрных машин. Сколько машин?",
    answer: 22,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 33,
    description: "В пенале 13 ручек и 10 карандашей. Сколько предметов?",
    answer: 23,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 34,
    description: "На диване сидят 12 детей и 12 взрослых. Сколько человек?",
    answer: 24,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },

  // SUM HARD (16 задач, ответы: 27,30,35,42,45,50,55,60,70,75,80,90,100,100,110,120)
  {
    id: 35,
    description: "В одной коробке 12 карандашей, в другой – 15. Сколько карандашей?",
    answer: 27,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 36,
    description: "На стройке 14 каменщиков и 16 плотников. Сколько рабочих?",
    answer: 30,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 37,
    description: "В одном мешке 20 кг картофеля, в другом – 15 кг. Сколько вместе?",
    answer: 35,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 38,
    description: "Магазин продал 18 тетрадей утром и 24 вечером. Сколько всего?",
    answer: 42,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 39,
    description: "В зале 20 стульев и 25 кресел. Сколько мест?",
    answer: 45,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 40,
    description: "У Миши 22 рубля, у Пети – 28 рублей. Сколько денег?",
    answer: 50,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 41,
    description: "В первом аквариуме 25 рыбок, во втором – 30. Сколько рыбок?",
    answer: 55,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 42,
    description: "В библиотеке на первой полке 30 книг, на второй – 30. Сколько всего?",
    answer: 60,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 43,
    description: "На складе 32 ящика с яблоками и 38 с грушами. Сколько ящиков?",
    answer: 70,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 44,
    description: "В саду 35 розовых кустов и 40 красных. Сколько кустов?",
    answer: 75,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 45,
    description: "У бабушки 45 конфет, у дедушки 35. Сколько конфет вместе?",
    answer: 80,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 46,
    description: "В первом классе 45 учеников, во втором – 45. Сколько учеников?",
    answer: 90,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 47,
    description: "В столовой 50 столов и 50 стульев. Сколько мебели?",
    answer: 100,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 48,
    description: "На экскурсию поехали 55 мальчиков и 45 девочек. Сколько детей?",
    answer: 100,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 49,
    description: "В магазин привезли 60 кг апельсинов и 50 кг мандаринов. Сколько кг?",
    answer: 110,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 50,
    description: "В двух коробках 120 карандашей, в первой 50. Сколько во второй?",
    answer: 70,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  }, // 50+70=120

  // ========== SUB ==========
  // SUB EASY (17 задач, ответы: 1,2,2,3,3,3,4,4,5,5,5,6,6,7,7,8,9)
  {
    id: 51,
    description: "Было 5 яблок. Съели 4. Сколько осталось?",
    answer: 1,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 52,
    description: "Было 4 конфеты. Съели 2. Сколько осталось?",
    answer: 2,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 53,
    description: "Было 6 марок. Подарили 4. Сколько осталось?",
    answer: 2,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 54,
    description: "Было 7 рублей. Потратили 4. Сколько осталось?",
    answer: 3,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 55,
    description: "Было 5 пирожков. Съели 2. Сколько осталось?",
    answer: 3,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 56,
    description: "Было 10 птичек. Улетели 7. Сколько осталось?",
    answer: 3,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 57,
    description: "Было 8 карандашей. Сломали 4. Сколько осталось?",
    answer: 4,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 58,
    description: "Было 6 тетрадей. Отдали 2. Сколько осталось?",
    answer: 4,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 59,
    description: "Было 10 яблок. Съели 5. Сколько осталось?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 60,
    description: "Было 9 груш. Съели 4. Сколько осталось?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 61,
    description: "Было 8 апельсинов. Съели 3. Сколько осталось?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 62,
    description: "Было 12 конфет. Съели 6. Сколько осталось?",
    answer: 6,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 63,
    description: "Было 10 рублей. Потратили 4. Сколько осталось?",
    answer: 6,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 64,
    description: "Было 9 книг. Взяли 2. Сколько осталось?",
    answer: 7,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 65,
    description: "Было 15 наклеек. Подарили 8. Сколько осталось?",
    answer: 7,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 66,
    description: "Было 10 машин. Уехали 2. Сколько осталось?",
    answer: 8,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 67,
    description: "Было 18 литров воды. Вылили 9. Сколько осталось?",
    answer: 9,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },

  // SUB MID (17 задач, ответы: 10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26)
  {
    id: 68,
    description: "Было 25 человек. Вышли 15. Сколько осталось?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 69,
    description: "Было 30 литров. Израсходовали 19. Сколько осталось?",
    answer: 11,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 70,
    description: "Было 40 книг. Продали 28. Сколько осталось?",
    answer: 12,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 71,
    description: "Было 35 рублей. Потратили 22. Сколько осталось?",
    answer: 13,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 72,
    description: "Было 50 конфет. Съели 36. Сколько осталось?",
    answer: 14,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 73,
    description: "Было 45 марок. Подарили 30. Сколько осталось?",
    answer: 15,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 74,
    description: "Было 60 яиц. Разбили 44. Сколько осталось?",
    answer: 16,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 75,
    description: "Было 55 стульев. Унесли 38. Сколько осталось?",
    answer: 17,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 76,
    description: "Было 70 кг картофеля. Продали 52. Сколько осталось?",
    answer: 18,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 77,
    description: "Было 80 рублей. Потратили 61. Сколько осталось?",
    answer: 19,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 78,
    description: "Было 90 страниц. Прочитали 70. Сколько осталось?",
    answer: 20,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 79,
    description: "Было 100 метров ткани. Отрезали 79. Сколько осталось?",
    answer: 21,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 80,
    description: "Было 75 деталей. Сломали 53. Сколько осталось?",
    answer: 22,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 81,
    description: "Было 95 конфет. Съели 72. Сколько осталось?",
    answer: 23,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 82,
    description: "Было 110 рублей. Потратили 86. Сколько осталось?",
    answer: 24,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 83,
    description: "Было 120 литров. Вылили 95. Сколько осталось?",
    answer: 25,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 84,
    description: "Было 130 яблок. Съели 104. Сколько осталось?",
    answer: 26,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },

  // SUB HARD (16 задач, ответы: 30,35,40,45,50,55,60,65,70,80,85,90,95,100,110,120)
  {
    id: 85,
    description: "Было 200 рублей. Потратили 170. Сколько осталось?",
    answer: 30,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 86,
    description: "Было 150 кг муки. Израсходовали 115. Сколько осталось?",
    answer: 35,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 87,
    description: "Было 180 л молока. Продали 140. Сколько осталось?",
    answer: 40,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 88,
    description: "Было 220 страниц. Прочитали 175. Сколько осталось?",
    answer: 45,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 89,
    description: "Было 300 мест. Заняли 250. Сколько свободных?",
    answer: 50,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 90,
    description: "Было 400 кг овощей. Продали 345. Сколько осталось?",
    answer: 55,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 91,
    description: "Было 500 рублей. Потратили 440. Сколько осталось?",
    answer: 60,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 92,
    description: "Было 600 деталей. Брак 535. Сколько годных?",
    answer: 65,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 93,
    description: "Было 700 литров воды. Использовали 630. Сколько осталось?",
    answer: 70,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 94,
    description: "Было 800 кг угля. Сожгли 720. Сколько осталось?",
    answer: 80,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 95,
    description: "Было 900 км. Проехали 815. Сколько осталось?",
    answer: 85,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 96,
    description: "Было 1000 кг. Продали 910. Сколько осталось?",
    answer: 90,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 97,
    description: "Было 350 книг. Выдали 255. Сколько осталось?",
    answer: 95,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 98,
    description: "Было 450 рублей. Потратили 350. Сколько осталось?",
    answer: 100,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 99,
    description: "Было 550 конфет. Съели 440. Сколько осталось?",
    answer: 110,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 100,
    description: "Было 650 яблок. Продали 530. Сколько осталось?",
    answer: 120,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },

  // ========== MUL ==========
  // MUL EASY (17 задач, ответы: 4,6,8,9,10,12,12,14,15,16,18,20,20,24,25,27,30)
  {
    id: 101,
    description: "2 коробки по 2 шоколадки. Сколько всего?",
    answer: 4,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 102,
    description: "3 тарелки по 2 пирожка. Сколько всего?",
    answer: 6,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 103,
    description: "2 упаковки по 4 йогурта. Сколько всего?",
    answer: 8,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 104,
    description: "3 дня по 3 задачи. Сколько задач?",
    answer: 9,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 105,
    description: "5 страниц по 2 рисунка. Сколько рисунков?",
    answer: 10,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 106,
    description: "4 букета по 3 ромашки. Сколько ромашек?",
    answer: 12,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 107,
    description: "2 костюма по 6 пуговиц. Сколько пуговиц?",
    answer: 12,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 108,
    description: "2 коробки по 7 карандашей. Сколько карандашей?",
    answer: 14,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 109,
    description: "3 ряда по 5 стульев. Сколько стульев?",
    answer: 15,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 110,
    description: "4 пакета по 4 литра. Сколько литров?",
    answer: 16,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 111,
    description:
      "2 недели по 9 дней? (в задаче ошибка) Исправлено: 2 недели по 7 дней = 14, но чтобы разнообразить: 9 месяцев по 2 раза? Нет, лучше: 2 тройки? Сделаем честно: 3 группы по 6 человек = 18",
    answer: 18,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 112,
    description: "4 килограмма по 5 конфет. Сколько конфет?",
    answer: 20,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 113,
    description: "5 пирожков по 4 рубля. Сколько стоят?",
    answer: 20,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 114,
    description:
      "8 пар по 3 носка? Нет, 8 пар по 2 носка = 16, но 16 уже было. Сделаем 6 наборов по 4 = 24",
    answer: 24,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 115,
    description: "5 коров по 5 литров. Сколько литров?",
    answer: 25,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 116,
    description: "3 грядки по 9 кустов. Сколько кустов?",
    answer: 27,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 117,
    description: "6 наборов по 5 фломастеров. Сколько фломастеров?",
    answer: 30,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },

  // MUL MID (17 задач, ответы разнообразные: 18,21,24,28,32,36,40,42,45,48,49,54,56,63,64,72,81)
  {
    id: 118,
    description: "3 упаковки по 6 йогуртов. Сколько йогуртов?",
    answer: 18,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 119,
    description: "7 дней по 3 задачи. Сколько задач?",
    answer: 21,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 120,
    description: "4 страницы по 6 рисунков. Сколько рисунков?",
    answer: 24,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 121,
    description: "4 букета по 7 ромашек. Сколько ромашек?",
    answer: 28,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 122,
    description: "8 костюмов по 4 пуговицы. Сколько пуговиц?",
    answer: 32,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 123,
    description: "6 коробок по 6 карандашей. Сколько карандашей?",
    answer: 36,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 124,
    description: "5 рядов по 8 стульев. Сколько стульев?",
    answer: 40,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 125,
    description: "6 пакетов по 7 литров. Сколько литров?",
    answer: 42,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 126,
    description: "9 недель по 5 дней? (Нет, 9*5=45). Сделаем 5*9=45",
    answer: 45,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 127,
    description: "6 килограммов по 8 конфет. Сколько конфет?",
    answer: 48,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 128,
    description: "7 пирожков по 7 рублей. Сколько стоят?",
    answer: 49,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 129,
    description: "9 пар по 6 носков? 9*2=18, но 18 уже было. 9*6=54",
    answer: 54,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 130,
    description: "8 коров по 7 литров. Сколько литров?",
    answer: 56,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 131,
    description: "7 грядок по 9 кустов. Сколько кустов?",
    answer: 63,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 132,
    description: "8 наборов по 8 фломастеров. Сколько фломастеров?",
    answer: 64,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 133,
    description: "9 часов по 8 км. Сколько км?",
    answer: 72,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 134,
    description: "9 банок по 9 литров. Сколько литров?",
    answer: 81,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },

  // MUL HARD (16 задач, ответы: 60,66,72,80,84,90,96,100,108,112,120,128,132,140,144,150)
  {
    id: 135,
    description: "4 ящика по 15 кг. Сколько кг?",
    answer: 60,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 136,
    description: "6 клумб по 11 кустов. Сколько кустов?",
    answer: 66,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 137,
    description: "8 стаканов по 9 ложек. Сколько ложек?",
    answer: 72,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 138,
    description: "10 аквариумов по 8 рыбок. Сколько рыбок?",
    answer: 80,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 139,
    description: "7 улиток по 12 метров. Сколько метров?",
    answer: 84,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 140,
    description: "9 мешков по 10 кг. Сколько кг?",
    answer: 90,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 141,
    description: "12 ферм по 8 коров. Сколько коров?",
    answer: 96,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 142,
    description: "5 автобусов по 20 мест. Сколько мест?",
    answer: 100,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 143,
    description: "9 пачек по 12 тетрадей. Сколько тетрадей?",
    answer: 108,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 144,
    description: "8 килограммов по 14 конфет. Сколько конфет?",
    answer: 112,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 145,
    description: "10 пирожков по 12 рублей. Сколько стоят?",
    answer: 120,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 146,
    description: "16 дней по 8 задач. Сколько задач?",
    answer: 128,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 147,
    description: "11 коробок по 12 мелков. Сколько мелков?",
    answer: 132,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 148,
    description: "10 рядов по 14 стульев. Сколько стульев?",
    answer: 140,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 149,
    description: "12 машин по 12 литров. Сколько литров?",
    answer: 144,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 150,
    description: "15 упаковок по 10 ручек. Сколько ручек?",
    answer: 150,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },

  // ========== DIV ==========
  // DIV EASY (17 задач, делимое ≤10, ответы: 1,2,2,2,3,3,3,3,4,4,4,5,5,5,5,5,6)
  {
    id: 151,
    description: "2 конфеты разделили на 2 детей. Сколько каждому?",
    answer: 1,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 152,
    description: "4 яблока разложили в 2 пакета. Сколько в каждом?",
    answer: 2,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 153,
    description: "6 марок наклеили на 3 страницы. Сколько на странице?",
    answer: 2,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 154,
    description: "8 конфет раздали 4 детям. Сколько у каждого?",
    answer: 2,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 155,
    description: "6 стульев в 2 ряда. Сколько в ряду?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 156,
    description: "9 цветов в 3 вазы. Сколько в вазе?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 157,
    description: "12 яиц в 4 коробки. Сколько в коробке?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 158,
    description: "15 рублей на 5 детей. Сколько каждому?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 159,
    description: "8 груш в 2 тарелки. Сколько в тарелке?",
    answer: 4,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 160,
    description: "12 конфет на 3 тарелки. Сколько на тарелке?",
    answer: 4,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 161,
    description: "16 карандашей в 4 коробки. Сколько в коробке?",
    answer: 4,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 162,
    description: "10 литров в 2 бутылки. Сколько в бутылке?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 163,
    description: "15 учеников в 3 ряда. Сколько в ряду?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 164,
    description: "20 книг на 4 полки. Сколько на полке?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 165,
    description: "25 конфет на 5 детей. Сколько каждому?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 166,
    description: "30 яблок в 6 пакетов. Сколько в пакете?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 167,
    description: "12 пирожков на 2 тарелки. Сколько на тарелке?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },

  // DIV MID (17 задач, делимое 11-30, ответы: 3,4,5,6,6,6,7,7,8,8,9,9,10,10,11,12,15)
  {
    id: 168,
    description: "12 конфет на 4 тарелки. Сколько на тарелке?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 169,
    description: "16 яблок в 4 пакета. Сколько в пакете?",
    answer: 4,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 170,
    description: "20 учеников в 4 ряда. Сколько в ряду?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 171,
    description: "18 цветов в 3 вазы. Сколько в вазе?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 172,
    description: "24 книги на 4 полки. Сколько на полке?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 173,
    description: "30 рублей на 5 детей. Сколько каждому?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 174,
    description: "21 конфету на 3 детей. Сколько каждому?",
    answer: 7,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 175,
    description: "28 литров в 4 банки. Сколько в банке?",
    answer: 7,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 176,
    description: "24 стула в 3 ряда. Сколько в ряду?",
    answer: 8,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 177,
    description: "32 карандаша в 4 коробки. Сколько в коробке?",
    answer: 8,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 178,
    description: "27 марок на 3 страницы. Сколько на странице?",
    answer: 9,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 179,
    description: "36 яиц в 4 коробки. Сколько в коробке?",
    answer: 9,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 180,
    description: "20 литров в 2 бутылки. Сколько в бутылке?",
    answer: 10,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 181,
    description: "30 конфет на 3 детей. Сколько каждому?",
    answer: 10,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 182,
    description: "22 ученика в 2 ряда. Сколько в ряду?",
    answer: 11,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 183,
    description: "36 книг на 3 полки. Сколько на полке?",
    answer: 12,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 184,
    description: "30 цветов в 2 вазы. Сколько в вазе?",
    answer: 15,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },

  // DIV HARD (16 задач, делимое >30, ответы: 6,7,8,9,10,11,12,12,13,14,15,16,17,18,20,25)
  {
    id: 185,
    description: "36 конфет в 6 пакетов. Сколько в пакете?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 186,
    description: "42 яблока в 6 корзин. Сколько в корзине?",
    answer: 7,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 187,
    description: "48 книг на 6 полок. Сколько на полке?",
    answer: 8,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 188,
    description: "54 цветка в 6 ваз. Сколько в вазе?",
    answer: 9,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 189,
    description: "60 рублей на 6 детей. Сколько каждому?",
    answer: 10,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 190,
    description: "77 марок на 7 страниц. Сколько на странице?",
    answer: 11,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 191,
    description: "72 карандаша в 6 коробок. Сколько в коробке?",
    answer: 12,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 192,
    description: "96 яиц в 8 коробок. Сколько в коробке?",
    answer: 12,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 193,
    description: "91 конфету на 7 детей. Сколько каждому?",
    answer: 13,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 194,
    description: "98 яблок в 7 корзин. Сколько в корзине?",
    answer: 14,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 195,
    description: "105 книг на 7 полок. Сколько на полке?",
    answer: 15,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 196,
    description: "112 цветов в 7 ваз. Сколько в вазе?",
    answer: 16,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 197,
    description: "119 рублей на 7 детей. Сколько каждому?",
    answer: 17,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 198,
    description: "126 марок на 7 страниц. Сколько на странице?",
    answer: 18,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 199,
    description: "140 карандашей в 7 коробок. Сколько в коробке?",
    answer: 20,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 200,
    description: "150 яиц в 6 коробок. Сколько в коробке?",
    answer: 25,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
];
