import { TASK_LEVELS_ENUM } from "../enums/tasks-levels.enum";
import { TASKS_TYPES_ENUM } from "../enums/tasks-types.enum";
import { TTask } from "../types/task.type";

export const TASK_LIST: TTask[] = [
  // ========== SUM ==========
  // SUM EASY
  {
    id: 1,
    description: "У Миши 1 конфета, а у Кати 2. Сколько всего конфет у детей?",
    answer: 3,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 2,
    description: "На столе лежат 2 книги и 2 тетради. Сколько всего предметов на столе?",
    answer: 4,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 3,
    description: "В вазе 3 яблока и 1 груша. Сколько фруктов в вазе?",
    answer: 4,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 4,
    description: "Маша съела 2 пирожка, а Саша – 3. Сколько пирожков съели дети вместе?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 5,
    description: "В одном аквариуме 4 рыбки, а в другом – 1. Сколько рыбок в двух аквариумах?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 6,
    description: "У Лены 3 открытки, а у Оли тоже 3. Сколько открыток у девочек?",
    answer: 6,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 7,
    description: "На полке стоят 2 синие машинки и 4 красные. Сколько всего машинок на полке?",
    answer: 6,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 8,
    description: "На горке катались 2 девочки и 5 мальчиков. Сколько всего детей на горке?",
    answer: 7,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 9,
    description: "В коробке лежат 3 зелёных и 4 синих карандаша. Сколько карандашей в коробке?",
    answer: 7,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 10,
    description: "У Пети 5 рублей, а у Коли 3. Сколько денег у мальчиков?",
    answer: 8,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 11,
    description: "В пенале лежат 2 ручки и 6 фломастеров. Сколько пишущих предметов в пенале?",
    answer: 8,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 12,
    description: "На дереве сидели 4 вороны и 5 сорок. Сколько птиц сидело на дереве?",
    answer: 9,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 13,
    description: "В букете 3 розы и 6 тюльпанов. Сколько цветов в букете?",
    answer: 9,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 14,
    description: "У бабушки 3 белых и 7 серых кроликов. Сколько кроликов у бабушки?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 15,
    description: "В гараже стоят 2 грузовика и 8 легковых машин. Сколько машин в гараже?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 16,
    description: "На тарелке лежат 4 пирожка и 6 булочек. Сколько выпечки на тарелке?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 17,
    description: "В шкафу висят 5 курток и 5 пальто. Сколько предметов верхней одежды в шкафу?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.EASY,
  },

  // SUM MID
  {
    id: 18,
    description: "В одной вазе 5 цветов, а в другой – 7. Сколько цветов в двух вазах?",
    answer: 12,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 19,
    description: "У Миши 6 конфет, а у Кати 7. Сколько конфет у детей вместе?",
    answer: 13,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 20,
    description: "На одной полке 8 книг, на другой – 5. Сколько книг на обеих полках?",
    answer: 13,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 21,
    description: "В пруду плавали 7 уток и 7 лебедей. Сколько птиц плавало в пруду?",
    answer: 14,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 22,
    description: "На площадке играли 8 девочек и 7 мальчиков. Сколько всего детей играло?",
    answer: 15,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 23,
    description: "В коробке 9 синих пуговиц и 6 белых. Сколько пуговиц в коробке?",
    answer: 15,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 24,
    description:
      "В первый день девочка прочитала 8 страниц, а во второй – 8. Сколько страниц она прочитала за два дня?",
    answer: 16,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 25,
    description: "Мама купила 6 кг яблок и 11 кг груш. Сколько килограммов фруктов купила мама?",
    answer: 17,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 26,
    description: "У Лены 9 наклеек, а у Кати – 8. Сколько наклеек у обеих девочек?",
    answer: 17,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 27,
    description: "В гараже 10 легковых и 8 грузовых машин. Сколько всего машин в гараже?",
    answer: 18,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 28,
    description: "На столе лежат 11 тетрадей и 8 книг. Сколько предметов на столе?",
    answer: 19,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 29,
    description: "В букете 10 ромашек и 10 васильков. Сколько цветов в букете?",
    answer: 20,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 30,
    description: "У Пети 12 рублей, а у Саши – 8. Сколько денег у мальчиков?",
    answer: 20,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 31,
    description: "В ящике 9 яблок и 12 груш. Сколько фруктов в ящике?",
    answer: 21,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 32,
    description: "На парковке 12 белых и 10 чёрных машин. Сколько машин на парковке?",
    answer: 22,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 33,
    description: "В пенале у Васи 13 ручек и 10 карандашей. Сколько предметов в пенале?",
    answer: 23,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 34,
    description: "На диване сидят 12 детей и 12 взрослых. Сколько человек сидит на диване?",
    answer: 24,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.MID,
  },

  // SUM HARD
  {
    id: 35,
    description:
      "В одной коробке 12 карандашей, а в другой – 15. Сколько карандашей в двух коробках?",
    answer: 27,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 36,
    description: "На стройке работают 14 каменщиков и 16 плотников. Сколько рабочих на стройке?",
    answer: 30,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 37,
    description:
      "В одном мешке 20 кг картофеля, а в другом – 15 кг. Сколько килограммов картофеля в двух мешках?",
    answer: 35,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 38,
    description:
      "Магазин продал утром 18 тетрадей, а вечером – 24. Сколько тетрадей продали за день?",
    answer: 42,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 39,
    description: "В зале 20 стульев и 25 кресел. Сколько мест для сидения в зале?",
    answer: 45,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 40,
    description: "У Миши 22 рубля, а у Пети – 28. Сколько денег у мальчиков вместе?",
    answer: 50,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 41,
    description: "В первом аквариуме 25 рыбок, во втором – 30. Сколько рыбок в двух аквариумах?",
    answer: 55,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 42,
    description: "На первой полке библиотеки 30 книг, на второй – 30. Сколько книг на двух полках?",
    answer: 60,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 43,
    description:
      "На складе 32 ящика с яблоками и 38 ящиков с грушами. Сколько всего ящиков на складе?",
    answer: 70,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 44,
    description: "В саду 35 розовых кустов и 40 красных. Сколько кустов роз в саду?",
    answer: 75,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 45,
    description: "У бабушки 45 конфет, а у дедушки 35. Сколько конфет у бабушки и дедушки вместе?",
    answer: 80,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 46,
    description: "В первом классе 45 учеников, во втором – 45. Сколько учеников в двух классах?",
    answer: 90,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 47,
    description: "В столовой 50 столов и 50 стульев. Сколько предметов мебели в столовой?",
    answer: 100,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 48,
    description:
      "На экскурсию поехали 55 мальчиков и 45 девочек. Сколько детей поехало на экскурсию?",
    answer: 100,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 49,
    description:
      "В магазин привезли 60 кг апельсинов и 50 кг мандаринов. Сколько килограммов цитрусовых привезли?",
    answer: 110,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 50,
    description:
      "В двух коробках 120 карандашей. В первой коробке 50 карандашей. Сколько карандашей во второй коробке?",
    answer: 70,
    type: TASKS_TYPES_ENUM.SUM,
    level: TASK_LEVELS_ENUM.HARD,
  },

  // ========== SUB ==========
  // SUB EASY
  {
    id: 51,
    description: "Было 5 яблок. 4 яблока съели. Сколько яблок осталось?",
    answer: 1,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 52,
    description: "У Пети было 4 конфеты. Он съел 2. Сколько конфет осталось?",
    answer: 2,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 53,
    description: "У Оли было 6 марок. Она подарила подруге 4 марки. Сколько марок осталось?",
    answer: 2,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 54,
    description: "У Миши было 7 рублей. Он потратил 4 рубля на мороженое. Сколько денег осталось?",
    answer: 3,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 55,
    description: "На тарелке было 5 пирожков. 2 пирожка съели. Сколько пирожков осталось?",
    answer: 3,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 56,
    description: "На ветке сидело 10 птичек. 7 улетели. Сколько птичек осталось на ветке?",
    answer: 3,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 57,
    description: "В коробке было 8 карандашей. 4 сломались. Сколько целых карандашей осталось?",
    answer: 4,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 58,
    description: "У Лены было 6 тетрадей. 2 тетради она отдала брату. Сколько тетрадей осталось?",
    answer: 4,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 59,
    description: "В вазе было 10 яблок. 5 яблок съели. Сколько яблок осталось?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 60,
    description: "В пакете было 9 груш. 4 груши съели. Сколько груш осталось?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 61,
    description: "В корзине было 8 апельсинов. 3 апельсина забрали. Сколько апельсинов осталось?",
    answer: 5,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 62,
    description: "В коробке было 12 конфет. Дети съели 6 конфет. Сколько конфет осталось?",
    answer: 6,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 63,
    description: "У Коли было 10 рублей. Он купил ручку за 4 рубля. Сколько денег осталось?",
    answer: 6,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 64,
    description: "В шкафу было 9 книг. 2 книги взяли почитать. Сколько книг осталось?",
    answer: 7,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 65,
    description:
      "У Кати было 15 наклеек. 8 наклеек она подарила подруге. Сколько наклеек осталось?",
    answer: 7,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 66,
    description: "На стоянке было 10 машин. 2 машины уехали. Сколько машин осталось?",
    answer: 8,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 67,
    description:
      "В бочке было 18 литров воды. Из неё вылили 9 литров. Сколько литров воды осталось?",
    answer: 9,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.EASY,
  },

  // SUB MID
  {
    id: 68,
    description:
      "В автобусе ехало 25 человек. На остановке вышли 15. Сколько человек осталось в автобусе?",
    answer: 10,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 69,
    description:
      "В бидоне было 30 литров молока. Израсходовали 19 литров. Сколько молока осталось?",
    answer: 11,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 70,
    description: "В магазине было 40 книг. Продали 28. Сколько книг осталось?",
    answer: 12,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 71,
    description: "У Пети было 35 рублей. Он потратил 22 рубля. Сколько денег осталось?",
    answer: 13,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 72,
    description: "В вазе было 50 конфет. Дети съели 36. Сколько конфет осталось?",
    answer: 14,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 73,
    description: "У Коли было 45 марок. Он подарил другу 30 марок. Сколько марок осталось?",
    answer: 15,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 74,
    description: "В коробке было 60 яиц. Разбили 44. Сколько целых яиц осталось?",
    answer: 16,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 75,
    description: "В актовом зале было 55 стульев. 38 стульев унесли. Сколько стульев осталось?",
    answer: 17,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 76,
    description: "В мешке было 70 кг картофеля. Продали 52 кг. Сколько картофеля осталось?",
    answer: 18,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 77,
    description: "У мамы было 80 рублей. Она потратила 61 рубль. Сколько денег осталось?",
    answer: 19,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 78,
    description: "В книге 90 страниц. Девочка прочитала 70. Сколько страниц осталось прочитать?",
    answer: 20,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 79,
    description: "В рулоне 100 метров ткани. Отрезали 79 метров. Сколько метров ткани осталось?",
    answer: 21,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 80,
    description: "В ящике было 75 деталей. 53 детали сломались. Сколько целых деталей осталось?",
    answer: 22,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 81,
    description: "В пакете было 95 конфет. Дети съели 72. Сколько конфет осталось?",
    answer: 23,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 82,
    description: "У Васи было 110 рублей. Он купил игрушку за 86 рублей. Сколько денег осталось?",
    answer: 24,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 83,
    description:
      "В бочке было 120 литров воды. На полив израсходовали 95 литров. Сколько воды осталось?",
    answer: 25,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 84,
    description: "В корзине было 130 яблок. 104 яблока продали. Сколько яблок осталось?",
    answer: 26,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.MID,
  },

  // SUB HARD
  {
    id: 85,
    description: "У Сергея было 200 рублей. Он потратил 170 рублей. Сколько денег осталось?",
    answer: 30,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 86,
    description: "На складе было 150 кг муки. Израсходовали 115 кг. Сколько муки осталось?",
    answer: 35,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 87,
    description: "В магазине было 180 литров молока. Продали 140 литров. Сколько молока осталось?",
    answer: 40,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 88,
    description:
      "В книге 220 страниц. Мальчик прочитал 175. Сколько страниц ему осталось прочитать?",
    answer: 45,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 89,
    description: "В кинотеатре 300 мест. Заняли 250. Сколько свободных мест осталось?",
    answer: 50,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 90,
    description: "На складе было 400 кг овощей. Продали 345 кг. Сколько овощей осталось?",
    answer: 55,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 91,
    description: "У Анны было 500 рублей. Она потратила 440 рублей. Сколько денег осталось?",
    answer: 60,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 92,
    description: "В партии было 600 деталей. Бракованных оказалось 535. Сколько годных деталей?",
    answer: 65,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 93,
    description:
      "В бассейне 700 литров воды. Для полива использовали 630 литров. Сколько воды осталось?",
    answer: 70,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 94,
    description: "На корабле 800 кг угля. Сожгли 720 кг. Сколько угля осталось?",
    answer: 80,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 95,
    description:
      "Путешественнику нужно проехать 900 км. Он проехал 815 км. Сколько километров осталось?",
    answer: 85,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 96,
    description: "В магазин завезли 1000 кг сахара. Продали 910 кг. Сколько сахара осталось?",
    answer: 90,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 97,
    description: "В библиотеке было 350 книг. Выдали читателям 255. Сколько книг осталось?",
    answer: 95,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 98,
    description:
      "У Николая было 450 рублей. Он купил подарок за 350 рублей. Сколько денег осталось?",
    answer: 100,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 99,
    description: "В вазе было 550 конфет. Съели 440. Сколько конфет осталось?",
    answer: 110,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 100,
    description: "В корзине было 650 яблок. Продали 530. Сколько яблок осталось?",
    answer: 120,
    type: TASKS_TYPES_ENUM.SUB,
    level: TASK_LEVELS_ENUM.HARD,
  },

  // ========== MUL ==========
  // MUL EASY
  {
    id: 101,
    description: "В одной коробке 2 шоколадки. Сколько шоколадок в 2 таких коробках?",
    answer: 4,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 102,
    description: "На одной тарелке 3 пирожка. Сколько пирожков на 2 таких тарелках?",
    answer: 6,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 103,
    description: "В одной упаковке 4 йогурта. Сколько йогуртов в 2 упаковках?",
    answer: 8,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 104,
    description: "Каждый день Саша решает 3 задачи. Сколько задач он решит за 3 дня?",
    answer: 9,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 105,
    description: "На одной странице 5 рисунков. Сколько рисунков на 2 страницах?",
    answer: 10,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 106,
    description: "В одном букете 3 ромашки. Сколько ромашек в 4 таких букетах?",
    answer: 12,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 107,
    description: "На один костюм пришивают 6 пуговиц. Сколько пуговиц нужно для 2 костюмов?",
    answer: 12,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 108,
    description: "В одной коробке 7 карандашей. Сколько карандашей в 2 коробках?",
    answer: 14,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 109,
    description: "В одном ряду 5 стульев. Сколько стульев в 3 рядах?",
    answer: 15,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 110,
    description: "Купили 4 пакета молока по 4 литра в каждом. Сколько литров молока купили?",
    answer: 16,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 111,
    description:
      "В трёх группах детского сада по 6 детей в каждой. Сколько всего детей в этих группах?",
    answer: 18,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 112,
    description: "В одном килограмме 5 конфет. Сколько конфет в 4 килограммах?",
    answer: 20,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 113,
    description: "Один пирожок стоит 4 рубля. Сколько стоят 5 таких пирожков?",
    answer: 20,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 114,
    description: "В одном наборе 6 фломастеров. Сколько фломастеров в 4 наборах?",
    answer: 24,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 115,
    description: "Одна корова даёт 5 литров молока в день. Сколько молока дают 5 коров?",
    answer: 25,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 116,
    description: "На одной грядке посадили 9 кустов клубники. Сколько кустов на 3 таких грядках?",
    answer: 27,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 117,
    description: "В одной пачке 6 фломастеров. Сколько фломастеров в 5 таких пачках?",
    answer: 30,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.EASY,
  },

  // MUL MID
  {
    id: 118,
    description: "В одной упаковке 6 йогуртов. Сколько йогуртов в 3 таких упаковках?",
    answer: 18,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 119,
    description: "Саша решает по 3 задачи в день. Сколько задач он решит за 7 дней?",
    answer: 21,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 120,
    description: "На одной странице 6 рисунков. Сколько рисунков на 4 страницах?",
    answer: 24,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 121,
    description: "В одном букете 7 ромашек. Сколько ромашек в 4 букетах?",
    answer: 28,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 122,
    description: "На каждый костюм пришивают 4 пуговицы. Сколько пуговиц нужно для 8 костюмов?",
    answer: 32,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 123,
    description: "В одной коробке 6 карандашей. Сколько карандашей в 6 коробках?",
    answer: 36,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 124,
    description: "В одном ряду 8 стульев. Сколько стульев в 5 рядах?",
    answer: 40,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 125,
    description:
      "Папа купил 6 пакетов молока по 7 литров в каждом. Сколько литров молока купил папа?",
    answer: 42,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 126,
    description: "В одной пачке 5 тетрадей. Сколько тетрадей в 9 таких пачках?",
    answer: 45,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 127,
    description: "В одном килограмме 8 конфет. Сколько конфет в 6 килограммах?",
    answer: 48,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 128,
    description: "Один пирожок стоит 7 рублей. Сколько стоят 7 таких пирожков?",
    answer: 49,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 129,
    description: "В одной коробке 6 ложек. Сколько ложек в 9 коробках?",
    answer: 54,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 130,
    description: "Одна корова даёт 7 литров молока в день. Сколько молока дают 8 коров?",
    answer: 56,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 131,
    description: "На одной грядке 9 кустов клубники. Сколько кустов на 7 грядках?",
    answer: 63,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 132,
    description: "В одном наборе 8 фломастеров. Сколько фломастеров в 8 наборах?",
    answer: 64,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 133,
    description: "Автомобиль едет 8 км в час. Сколько километров он проедет за 9 часов?",
    answer: 72,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 134,
    description: "В одной банке 9 литров сока. Сколько литров сока в 9 банках?",
    answer: 81,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.MID,
  },

  // MUL HARD
  {
    id: 135,
    description: "В одном ящике 15 кг яблок. Сколько килограммов яблок в 4 ящиках?",
    answer: 60,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 136,
    description: "На одной клумбе посадили 11 кустов роз. Сколько кустов на 6 таких клумбах?",
    answer: 66,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 137,
    description: "Один стакан вмещает 9 ложек сахара. Сколько ложек сахара нужно для 8 стаканов?",
    answer: 72,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 138,
    description: "В одном аквариуме 8 рыбок. Сколько рыбок в 10 аквариумах?",
    answer: 80,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 139,
    description:
      "Одна улитка за час проползает 12 метров. Сколько метров проползут 7 улиток за час?",
    answer: 84,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 140,
    description: "В одном мешке 10 кг картофеля. Сколько килограммов в 9 мешках?",
    answer: 90,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 141,
    description: "На одной ферме 8 коров. Сколько коров на 12 таких фермах?",
    answer: 96,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 142,
    description: "В одном автобусе 20 мест. Сколько мест в 5 автобусах?",
    answer: 100,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 143,
    description: "В одной пачке 12 тетрадей. Сколько тетрадей в 9 пачках?",
    answer: 108,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 144,
    description: "В одном килограмме 14 конфет. Сколько конфет в 8 килограммах?",
    answer: 112,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 145,
    description: "Один пирожок стоит 12 рублей. Сколько стоят 10 пирожков?",
    answer: 120,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 146,
    description: "Каждый день Саша решает 8 задач. Сколько задач он решит за 16 дней?",
    answer: 128,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 147,
    description: "В одной коробке 12 мелков. Сколько мелков в 11 коробках?",
    answer: 132,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 148,
    description: "В одном ряду 14 стульев. Сколько стульев в 10 рядах?",
    answer: 140,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 149,
    description:
      "Одна машина расходует 12 литров бензина. Сколько литров бензина расходуют 12 машин?",
    answer: 144,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 150,
    description: "В одной упаковке 10 ручек. Сколько ручек в 15 упаковках?",
    answer: 150,
    type: TASKS_TYPES_ENUM.MUL,
    level: TASK_LEVELS_ENUM.HARD,
  },

  // ========== DIV ==========
  // DIV EASY
  {
    id: 151,
    description: "2 конфеты разделили поровну между 2 детьми. Сколько конфет получил каждый?",
    answer: 1,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 152,
    description: "4 яблока разложили поровну в 2 пакета. Сколько яблок в каждом пакете?",
    answer: 2,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 153,
    description: "6 марок наклеили поровну на 3 страницы. Сколько марок на каждой странице?",
    answer: 2,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 154,
    description: "8 конфет раздали поровну 4 детям. Сколько конфет получил каждый?",
    answer: 2,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 155,
    description: "6 стульев расставили в 2 ряда поровну. Сколько стульев в каждом ряду?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 156,
    description: "9 цветов поставили в 3 вазы поровну. Сколько цветов в каждой вазе?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 157,
    description: "12 яиц разложили в 4 коробки поровну. Сколько яиц в каждой коробке?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 158,
    description: "15 рублей разделили поровну между 5 детьми. Сколько рублей получил каждый?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 159,
    description: "8 груш разложили поровну на 2 тарелки. Сколько груш на каждой тарелке?",
    answer: 4,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 160,
    description: "12 конфет разложили поровну на 3 тарелки. Сколько конфет на каждой тарелке?",
    answer: 4,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 161,
    description:
      "16 карандашей разложили поровну в 4 коробки. Сколько карандашей в каждой коробке?",
    answer: 4,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 162,
    description: "10 литров сока разлили поровну в 2 бутылки. Сколько литров в каждой бутылке?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 163,
    description: "15 учеников построили в 3 ряда поровну. Сколько учеников в каждом ряду?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 164,
    description: "20 книг расставили на 4 полки поровну. Сколько книг на каждой полке?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 165,
    description: "25 конфет разделили поровну между 5 детьми. Сколько конфет получил каждый?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 166,
    description: "30 яблок разложили поровну в 6 пакетов. Сколько яблок в каждом пакете?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },
  {
    id: 167,
    description: "12 пирожков разложили поровну на 2 тарелки. Сколько пирожков на каждой тарелке?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.EASY,
  },

  // DIV MID
  {
    id: 168,
    description: "12 конфет разложили поровну на 4 тарелки. Сколько конфет на каждой тарелке?",
    answer: 3,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 169,
    description: "16 яблок разложили поровну в 4 пакета. Сколько яблок в каждом пакете?",
    answer: 4,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 170,
    description: "20 учеников разделили на 4 равные команды. Сколько учеников в каждой команде?",
    answer: 5,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 171,
    description: "18 цветов поставили поровну в 3 вазы. Сколько цветов в каждой вазе?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 172,
    description: "24 книги расставили поровну на 4 полки. Сколько книг на каждой полке?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 173,
    description: "30 рублей разделили поровну между 5 детьми. Сколько рублей получил каждый?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 174,
    description: "21 конфету раздали поровну 3 детям. Сколько конфет получил каждый?",
    answer: 7,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 175,
    description: "28 литров сока разлили поровну в 4 банки. Сколько литров в каждой банке?",
    answer: 7,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 176,
    description: "24 стула расставили в 3 ряда поровну. Сколько стульев в каждом ряду?",
    answer: 8,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 177,
    description: "32 карандаша разложили поровну в 4 коробки. Сколько карандашей в каждой коробке?",
    answer: 8,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 178,
    description: "27 марок наклеили поровну на 3 страницы. Сколько марок на каждой странице?",
    answer: 9,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 179,
    description: "36 яиц разложили поровну в 4 коробки. Сколько яиц в каждой коробке?",
    answer: 9,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 180,
    description: "20 литров воды разлили поровну в 2 бочки. Сколько литров в каждой бочке?",
    answer: 10,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 181,
    description: "30 конфет раздали поровну 3 детям. Сколько конфет получил каждый?",
    answer: 10,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 182,
    description: "22 ученика построили в 2 ряда поровну. Сколько учеников в каждом ряду?",
    answer: 11,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 183,
    description: "36 книг расставили поровну на 3 полки. Сколько книг на каждой полке?",
    answer: 12,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },
  {
    id: 184,
    description: "30 цветов поставили поровну в 2 вазы. Сколько цветов в каждой вазе?",
    answer: 15,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.MID,
  },

  // DIV HARD
  {
    id: 185,
    description: "36 конфет разложили поровну в 6 пакетов. Сколько конфет в каждом пакете?",
    answer: 6,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 186,
    description: "42 яблока разложили поровну в 6 корзин. Сколько яблок в каждой корзине?",
    answer: 7,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 187,
    description: "48 книг расставили поровну на 6 полок. Сколько книг на каждой полке?",
    answer: 8,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 188,
    description: "54 цветка поставили поровну в 6 ваз. Сколько цветков в каждой вазе?",
    answer: 9,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 189,
    description: "60 рублей разделили поровну между 6 детьми. Сколько рублей получил каждый?",
    answer: 10,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 190,
    description: "77 марок наклеили поровну на 7 страниц. Сколько марок на каждой странице?",
    answer: 11,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 191,
    description: "72 карандаша разложили поровну в 6 коробок. Сколько карандашей в каждой коробке?",
    answer: 12,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 192,
    description: "96 яиц разложили поровну в 8 коробок. Сколько яиц в каждой коробке?",
    answer: 12,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 193,
    description: "91 конфету раздали поровну 7 детям. Сколько конфет получил каждый?",
    answer: 13,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 194,
    description: "98 яблок разложили поровну в 7 корзин. Сколько яблок в каждой корзине?",
    answer: 14,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 195,
    description: "105 книг расставили поровну на 7 полок. Сколько книг на каждой полке?",
    answer: 15,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 196,
    description: "112 цветов поставили поровну в 7 ваз. Сколько цветов в каждой вазе?",
    answer: 16,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 197,
    description: "119 рублей разделили поровну между 7 детьми. Сколько рублей получил каждый?",
    answer: 17,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 198,
    description: "126 марок наклеили поровну на 7 страниц. Сколько марок на каждой странице?",
    answer: 18,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 199,
    description:
      "140 карандашей разложили поровну в 7 коробок. Сколько карандашей в каждой коробке?",
    answer: 20,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
  {
    id: 200,
    description: "150 яиц разложили поровну в 6 коробок. Сколько яиц в каждой коробке?",
    answer: 25,
    type: TASKS_TYPES_ENUM.DIV,
    level: TASK_LEVELS_ENUM.HARD,
  },
];
