export enum GAME_ACTIONS_ENUM {
  GENERATE_INIT_FIELDSTATE = "GENERATE_INIT_FIELDSTATE",
  SHUFFLE_FIELDSTATE = "SHUFFLE_FIELDSTATE",
  BALL_CLICK = "BALL_CLICK",
  ROTATE_LAYER = "ROTATE_LAYER",
  ROTATE_EMPTY_SLOT_LAYER = "ROTATE_EMPTY_SLOT_LAYER",
}
